name: Test without cbp integration - Evidence

on:
  push:
    branches: test-publish-evidence
  workflow_dispatch:
  
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run My Custom Go Action
        uses: cloudbees-io-gha/publish-evidence-item@CBP-13628
        id: go-action
        with:
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.CBP_PAT }}
          content: "test content"
