name: Test without cbp integration - TestResult

on:
  push:
    branches: test-publish-test-result
  workflow_dispatch:
  
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Junit
        uses: cloudbees-io-gha/publish-evidence-item@test1
        with:
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.CBP_PAT }}
          test-type: junit
          result-path: test_data/junit/report*.xml
