name: Test without cbp integration - RunCBPWorkflow

on:
  push:
    branches: test-run-cbp-workflow
  workflow_dispatch:
  
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run My Custom Go Action
        uses: cloudbees-io-gha/run-cloudbees-workflow@CBP-13628
        id: go-action
        with:
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.CBP_PAT }}
          branch-name: "test-run-cbp-workflow"
          workflow-file-name: "test-workflow.yaml"
